
CREATE PROCEDURE SP_CadastraNovaNotaFiscal
	@NUM_NOTA_FISCAL int,
	@FORNECEDOR_CNPJ varchar(14),
	@DATA_NOTA_FISCAL DATE,
	@VALOR_NOTA_FISCAL FLOAT,
	@DATA_RECEBIMENTO DATE
	AS
	BEGIN
		INSERT INTO tab_notas_fiscais ( 
			NOTA_FISCAL_NUM, 
			FORNECEDOR_CNPJ, 
			NOTA_FISCAL_DATA, 
			NOTA_FISCAL_VALOR, 
			NOTA_FISCAL_DATA_RECEBIMENTO
			)
		VALUES (
			@NUM_NOTA_FISCAL,
			@FORNECEDOR_CNPJ,
			@DATA_NOTA_FISCAL,
			@VALOR_NOTA_FISCAL,
			@DATA_RECEBIMENTO
			)
	END
GO



