

CREATE PROCEDURE SP_TempCadastraNovoItemDeNotaFiscal
	@NUM_NOTA_FISCAL INT,
	@FORNECEDOR_CNPJ VARCHAR(14),
	@DESCRICAO_ITEM_NOTA_FISCAL VARCHAR(255),
	@QUANTIDADE_ITEM INT,
	@VALOR_ITEM FLOAT,
	AS
	BEGIN
		INSERT INTO TAB_TEMP_ITENS_NOTAS_FISCAIS (
				NUM_NOTA_FISCAL,
				FORNECEDOR_CNPJ,
				DESCRICAO_ITEM_NOTA_FISCAL,
				QUANTIDADE_ITEM,
				VALOR_ITEM
				)
		VALUES (
				@NUM_NOTA_FISCAL,
				@FORNECEDOR_CNPJ,
				@DESCRICAO_ITEM_NOTA_FISCAL,
				@QUANTIDADE_ITEM,
				@VALOR_ITEM)
			END
GO